// api/_lib/pit/commercialReasoning.js
// Commercial Reasoning Engine: explains what matters most and why.

export function buildCommercialReasoning({ metrics, paymentsStack, commercialIntelligence, opportunities }) {
  const top=opportunities?.[0]||null;
  const reasoning={ primaryCommercialTheme:null, whyItMatters:null, whatToIgnoreForNow:[], highestPriority: top?{id:top.id,title:top.title,rationale:buildPriorityRationale(top),evidence:top.evidence||[]}:null, supportingPriorities:(opportunities||[]).slice(1,4).map(opp=>({id:opp.id,title:opp.title,rationale:buildPriorityRationale(opp),evidence:opp.evidence||[]})), storyArc:['Payments market context explains why the review matters.','Merchant facts establish the current position.','Fee and stack analysis show what is visible and what is missing.','Diagnostic modules explore only the most relevant findings.','Opportunity summary brings the commercial value together.'] };
  if(top?.id==='least-cost-routing'){ reasoning.primaryCommercialTheme='Debit routing appears to be the most important validation area.'; reasoning.whyItMatters='The merchant has a meaningful debit mix and LCR status is not confirmed, so routing may matter more than provider margin.'; }
  else if(top?.id==='october-reform'){ reasoning.primaryCommercialTheme='Upcoming interchange reform is the clearest commercial catalyst.'; reasoning.whyItMatters='Credit volume is visible and reforms have a confirmed start date, making pass-through validation commercially important.'; }
  else if(top?.id==='pricing-structure'){ reasoning.primaryCommercialTheme='Pricing structure is the key commercial area to validate.'; reasoning.whyItMatters='Provider margin, pricing transparency and cost composition determine whether the merchant can capture savings.'; }
  else { reasoning.primaryCommercialTheme='The PIT identified several areas requiring validation.'; reasoning.whyItMatters='The current data supports a diagnostic review but additional inputs would improve certainty.'; }
  if(commercialIntelligence.providerMargin?.position==='Competitive')reasoning.whatToIgnoreForNow.push('Do not over-focus on provider margin if it already appears commercially lean.');
  if(!metrics.feeComposition)reasoning.whatToIgnoreForNow.push('Do not over-interpret fee composition until detailed fee lines are available.');
  return reasoning;
}
function buildPriorityRationale(opp){ if(opp.id==='least-cost-routing')return'Debit volume is material and routing status is not confirmed, making this a practical area to validate before focusing on smaller commercial levers.'; if(opp.id==='october-reform')return'The reform has a confirmed commencement date and directly affects consumer credit interchange, so pass-through should be validated ahead of time.'; if(opp.id==='surcharge-planning')return'The surcharge rules change in October 2026, so the merchant needs a clear view of card cost absorption and pricing impact.'; if(opp.id==='pricing-structure')return'Pricing structure determines whether wholesale reductions, routing benefits and provider margin can be transparently assessed.'; return'This opportunity is relevant based on the current evidence and should be validated with additional context.'; }
