// api/_lib/pit/identifyOpportunities.js
// Opportunity Intelligence: identifies, quantifies and prioritises commercial opportunities.

import { moneyBand, urgencyRank, confidenceRank } from './utils.js';

export function identifyOpportunities({ facts, metrics, paymentsStack, commercialIntelligence, riskIntelligence }) {
  const opportunities=[];
  const lcrConfirmedOn=/^(on|enabled|active|yes)$/i.test(facts.lcrStatus||''); const lcrUnavailable=/^(not applicable|n\/a|na)$/i.test(facts.lcrStatus||'');
  if(metrics.cardMix?.debitPct>0 && !lcrConfirmedOn && !lcrUnavailable && metrics.lcrSavings)opportunities.push({id:'least-cost-routing',title:'Debit routing / least-cost routing',category:'Cost reduction',estimatedAnnualValue:metrics.lcrSavings.annual,valueBand:moneyBand(metrics.lcrSavings.annual),confidence:facts.lcrStatus==='Off'?'Likely':'Needs validation',urgency:'Medium',complexity:'Medium',evidence:[`${metrics.cardMix.debitPct}% debit mix`,`LCR status observed as ${facts.lcrStatus||'Unknown'}`],dependencies:['Confirm routing by channel','Confirm provider/gateway LCR capability'],module:'lcr'});
  if(metrics.reformSavings)opportunities.push({id:'october-reform',title:'October 2026 interchange reform',category:'Regulatory change',estimatedAnnualValue:metrics.reformSavings.annual,valueBand:moneyBand(metrics.reformSavings.annual),confidence:'Estimated',urgency:'High',complexity:'Low',evidence:['Credit card turnover detected','Consumer credit interchange cap changes from 1 October 2026'],dependencies:['Confirm consumer vs commercial credit split','Confirm provider pass-through'],module:'reform'});
  if(paymentsStack.surchargeStatus!=='Not indicated')opportunities.push({id:'surcharge-planning',title:'Surcharge strategy before October 2026',category:'Regulatory / margin planning',estimatedAnnualValue:null,valueBand:'Strategic',confidence:'Needs validation',urgency:'High',complexity:'Medium',evidence:[`Surcharge status: ${paymentsStack.surchargeStatus}`],dependencies:['Confirm current surcharge approach','Model margin impact after surcharge removal'],module:'surcharge'});
  if(commercialIntelligence.pricingModel?.model)opportunities.push({id:'pricing-structure',title:'Pricing structure and provider margin',category:'Commercial review',estimatedAnnualValue:null,valueBand:'Strategic',confidence:commercialIntelligence.providerMargin?.observed?'Confirmed':'Needs validation',urgency:commercialIntelligence.providerMargin?.position==='Needs review'?'High':'Medium',complexity:'Low',evidence:[`Pricing model: ${commercialIntelligence.pricingModel.model}`],dependencies:['Validate all fees billed outside the acquirer statement'],module:'pricing'});
  if(riskIntelligence.risks?.some(r=>r.id==='incomplete-cost-risk'))opportunities.push({id:'total-cost-visibility',title:'True total cost of acceptance',category:'Data completeness',estimatedAnnualValue:null,valueBand:'Strategic',confidence:'Likely',urgency:'Medium',complexity:'Low',evidence:['Gateway costs may be billed separately'],dependencies:['Upload gateway invoice or transaction report'],module:'stack'});
  return opportunities.sort(compareOpportunities);
}
function compareOpportunities(a,b){ const va=Number(a.estimatedAnnualValue)||0, vb=Number(b.estimatedAnnualValue)||0; if(va!==vb)return vb-va; if(urgencyRank(a.urgency)!==urgencyRank(b.urgency))return urgencyRank(b.urgency)-urgencyRank(a.urgency); return confidenceRank(b.confidence)-confidenceRank(a.confidence); }
